# Production Environment Configuration
spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/staging_db_47yg
    username: staging_user
    password: 7hCfQr0LILXp6l55qQbMa1bgVFOvPCIe
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

logging:
  level:
    com.phonepe.payment: ERROR
    org.springframework.web.reactive.function.client: ERROR
    reactor.netty.http.client: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR
    org.apache: ERROR
    com.zaxxer.hikari: ERROR
    root: ERROR

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

dqr:
  phonepe:
    saltKey: ${PHONEPE_DQR_SALT_KEY}
    saltIndex: 1
    baseUrl: https://api.phonepe.com/apis/hermes
    endpoint: /v3/qr/init
    expiresIn: 3600
    numeric: 0123456789
    callback: https://prod-callback.yourcompany.com/phonepe/callback
    refundEndPoint: /v3/credit/backToSource
    cancelEndPoint: /v3/charge/
    cancelEndPointPath: /cancel
    checkPaymentStatusEndPoint: /v3/transaction/
    checkPaymentStatusEndPointPath: /status

edc:
  phonepe:
    merchantType: OFFLINE_ORGANISED,
    saltKey: ${PHONEPE_EDC_SALT_KEY}
    saltIndex: 1
    baseUrl: https://api.phonepe.com/apis/hermes
    endpoint: /v1/edc/transaction/init
    expiresIn: 3600
    numeric: 0123456789
    callback: https://prod-callback.yourcompany.com/phonepe/callback
    checkPaymentStatusEndPoint: /v1/edc/transaction/
    checkPaymentStatusEndPointPath: /status

payment:
  phonepe:
    saltKey: ${PHONEPE_PAYMENT_SALT_KEY}
    saltIndex: 1
    baseUrl: https://api.phonepe.com/apis/hermes
    endpoint: /v3/payLink/init
    expiresIn: 3600
    numeric: 0123456789
    callback: https://prod-callback.yourcompany.com/phonepe/callback

static:
  phonepe:
    saltKey: ${PHONEPE_STATIC_SALT_KEY}
    saltIndex: 1
    baseUrl: https://api.phonepe.com/apis/hermes
    endpoint: /v3/qr/transaction/list
    metadataEndpoint: /v1/merchant/transaction/metadata
    numeric: 0123456789
    callback: https://prod-callback.yourcompany.com/phonepe/callback

collect:
  phonepe:
    saltKey: ${PHONEPE_COLLECT_SALT_KEY}
    saltIndex: 1
    baseUrl: https://api.phonepe.com/apis/hermes
    endpoint: /v3/charge
    numeric: 0123456789
    callback: https://prod-callback.yourcompany.com/phonepe/callback

phonepe:
  api:
    connection:
      timeout: 60000
    read:
      timeout: 60000
    write:
      timeout: 60000
    retry:
      max-attempts: 5
      initial-delay: 3000