# Development Environment Configuration
spring:
  datasource:
    url: jdbc:postgresql://dpg-d39rpjmmcj7s739jdoqg-a:5432/staging_db_47yg
    username: staging_user
    password: 7hCfQr0LILXp6l55qQbMa1bgVFOvPCIe
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com.phonepe.payment: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework: WARN
    org.hibernate: WARN
    org.apache: WARN
    com.zaxxer.hikari: WARN

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

dqr:
  phonepe:
    saltKey: d07b3506-be23-44eb-95e8-2c4ab57bde62
    saltIndex: 1
    baseUrl: https://mercury-uat.phonepe.com/enterprise-sandbox
    endpoint: /v3/qr/init
    expiresIn: 1000
    numeric: 0123456789
    callback: https://webhook.site/432b4384-1da8-412f-9a27-e82b778b2ed2
    refundEndPoint: /v3/credit/backToSource
    cancelEndPoint: /v3/charge/
    cancelEndPointPath: /cancel
    checkPaymentStatusEndPoint: /v3/transaction/
    checkPaymentStatusEndPointPath: /status

edc:
  phonepe:
    merchantType: OFFLINE_ORGANISED,
    saltKey: d07b3506-be23-44eb-95e8-2c4ab57bde62
    saltIndex: 1
    baseUrl: https://mercury-uat.phonepe.com/enterprise-sandbox
    endpoint: /v1/edc/transaction/init
    expiresIn: 1000
    numeric: 0123456789
    callback: https://webhook.site/432b4384-1da8-412f-9a27-e82b778b2ed2
    checkPaymentStatusEndPoint: /v1/edc/transaction/
    checkPaymentStatusEndPointPath: /status

payment:
  phonepe:
    saltKey: d07b3506-be23-44eb-95e8-2c4ab57bde62
    saltIndex: 1
    baseUrl: https://mercury-uat.phonepe.com/enterprise-sandbox
    endpoint: /v3/payLink/init
    expiresIn: 1000
    numeric: 0123456789
    callback: https://webhook.site/432b4384-1da8-412f-9a27-e82b778b2ed2

static:
  phonepe:
    saltKey: d07b3506-be23-44eb-95e8-2c4ab57bde62
    saltIndex: 1
    baseUrl: https://mercury-uat.phonepe.com/enterprise-sandbox
    endpoint: /v3/qr/transaction/list
    metadataEndpoint: /v1/merchant/transaction/metadata
    numeric: 0123456789
    callback: https://webhook.site/432b4384-1da8-412f-9a27-e82b778b2ed2

collect:
  phonepe:
    saltKey: d07b3506-be23-44eb-95e8-2c4ab57bde62
    saltIndex: 1
    baseUrl: https://mercury-uat.phonepe.com/enterprise-sandbox
    endpoint: /v3/charge
    numeric: 0123456789
    callback: https://webhook.site/432b4384-1da8-412f-9a27-e82b778b2ed2

phonepe:
  api:
    connection:
      timeout: 30000
    read:
      timeout: 30000
    write:
      timeout: 30000
    retry:
      max-attempts: 3
      initial-delay: 1000