# Main Application Configuration - Common settings across all profiles
spring:
  profiles:
    active: staging

logging:
  file:
    name: logs/unified-payment-middleware-backend
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"