# Production Environment Configuration
server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://dpg-d39rpjmmcj7s739jdoqg-a:5432/prod_db_47yg
    username: prod_user
    password: 7hCfQr0LILXp6l55qQbMa1bgVFOvPCIe
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com.phonepe.payment: ERROR
    org.springframework.web.reactive.function.client: ERROR
    reactor.netty.http.client: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR
    org.apache: ERROR
    com.zaxxer.hikari: ERROR
    root: ERROR

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

dqr:
  phonepe:
    saltKey: d07b3506-be23-44eb-95e8-2c4ab57bde62
    saltIndex: 1
    baseUrl: https://mercury-uat.phonepe.com/enterprise-sandbox
    endpoint: /v3/qr/init
    expiresIn: 1000
    numeric: 0123456789
    callback: https://payment-middleware-backend.onrender.com/api/phonepe/s2s-callback
    refundEndPoint: /v3/credit/backToSource
    cancelEndPoint: /v3/charge/
    cancelEndPointPath: /cancel
    checkPaymentStatusEndPoint: /v3/transaction/
    checkPaymentStatusEndPointPath: /status

edc:
  phonepe:
    merchantType: OFFLINE_ORGANISED,
    saltKey: d07b3506-be23-44eb-95e8-2c4ab57bde62
    saltIndex: 1
    baseUrl: https://mercury-uat.phonepe.com/enterprise-sandbox
    endpoint: /v1/edc/transaction/init
    expiresIn: 1000
    numeric: 0123456789
    callback: https://payment-middleware-backend.onrender.com/api/phonepe/s2s-callback
    checkPaymentStatusEndPoint: /v1/edc/transaction/
    checkPaymentStatusEndPointPath: /status

payment:
  phonepe:
    saltKey: d07b3506-be23-44eb-95e8-2c4ab57bde62
    saltIndex: 1
    baseUrl: https://mercury-uat.phonepe.com/enterprise-sandbox
    endpoint: /v3/payLink/init
    expiresIn: 1000
    numeric: 0123456789
    callback: https://payment-middleware-backend.onrender.com/api/phonepe/s2s-callback

static:
  phonepe:
    saltKey: d07b3506-be23-44eb-95e8-2c4ab57bde62
    saltIndex: 1
    baseUrl: https://mercury-uat.phonepe.com/enterprise-sandbox
    endpoint: /v3/qr/transaction/list
    metadataEndpoint: /v1/merchant/transaction/metadata
    numeric: 0123456789
    callback: https://payment-middleware-backend.onrender.com/api/phonepe/s2s-callback

collect:
  phonepe:
    saltKey: d07b3506-be23-44eb-95e8-2c4ab57bde62
    saltIndex: 1
    baseUrl: https://mercury-uat.phonepe.com/enterprise-sandbox
    endpoint: /v3/charge
    numeric: 0123456789
    callback: https://payment-middleware-backend.onrender.com/api/phonepe/s2s-callback

phonepe:
  api:
    connection:
      timeout: 10000  # Reduced to 10s for faster failure detection
      pool:
        max-connections: 500
        pending-acquire-max: 1000
        max-idle-time: 45000  # Keep connections warm longer (45s)
        max-life-time: 300000  # 5 minutes max lifetime
        evict-interval: 60000  # Check every 60s (less overhead)
    read:
      timeout: 30000
    write:
      timeout: 10000  # Reduced to 10s for faster failure detection
    retry:
      max-attempts: 2  # Reduced to 2 attempts (1 retry) for faster failure
      initial-delay: 500  # Faster retry: 500ms instead of 1000ms