# Staging Environment Configuration
spring:
  datasource:
    url: jdbc:mysql://staging-db-host:3306/db_staging
    username: staging_user
    password: staging_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.phonepe.payment: INFO
    org.springframework.web.reactive.function.client: WARN
    reactor.netty.http.client: WARN
    org.springframework: WARN
    org.hibernate: WARN
    org.apache: WARN
    com.zaxxer.hikari: WARN

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

dqr:
  phonepe:
    saltKey: staging-salt-key-here
    saltIndex: 1
    baseUrl: https://mercury-staging.phonepe.com/enterprise
    endpoint: /v3/qr/init
    expiresIn: 1000
    numeric: 0123456789
    callback: https://staging-callback.yourcompany.com/phonepe/callback
    refundEndPoint: /v3/credit/backToSource
    cancelEndPoint: /v3/charge/
    cancelEndPointPath: /cancel
    checkPaymentStatusEndPoint: /v3/transaction/
    checkPaymentStatusEndPointPath: /status

edc:
  phonepe:
    merchantType: OFFLINE_ORGANISED,
    saltKey: staging-salt-key-here
    saltIndex: 1
    baseUrl: https://mercury-staging.phonepe.com/enterprise
    endpoint: /v1/edc/transaction/init
    expiresIn: 1000
    numeric: 0123456789
    callback: https://staging-callback.yourcompany.com/phonepe/callback
    checkPaymentStatusEndPoint: /v1/edc/transaction/
    checkPaymentStatusEndPointPath: /status

payment:
  phonepe:
    saltKey: staging-salt-key-here
    saltIndex: 1
    baseUrl: https://mercury-staging.phonepe.com/enterprise
    endpoint: /v3/payLink/init
    expiresIn: 1000
    numeric: 0123456789
    callback: https://staging-callback.yourcompany.com/phonepe/callback

static:
  phonepe:
    saltKey: staging-salt-key-here
    saltIndex: 1
    baseUrl: https://mercury-staging.phonepe.com/enterprise
    endpoint: /v3/qr/transaction/list
    metadataEndpoint: /v1/merchant/transaction/metadata
    numeric: 0123456789
    callback: https://staging-callback.yourcompany.com/phonepe/callback

collect:
  phonepe:
    saltKey: staging-salt-key-here
    saltIndex: 1
    baseUrl: https://mercury-staging.phonepe.com/enterprise
    endpoint: /v3/charge
    numeric: 0123456789
    callback: https://staging-callback.yourcompany.com/phonepe/callback

phonepe:
  api:
    connection:
      timeout: 30000
    read:
      timeout: 30000
    write:
      timeout: 30000
    retry:
      max-attempts: 3
      initial-delay: 1000