package com.phonepe.payment.dqr.entity;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "dqr_refund_transactions_response")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DqrRefundTransactionResponse {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(hidden = true) // Hide internal DB id from Swagger docs
    private Long id;

    @Schema(description = "Unique refund transaction ID generated by PhonePe", example = "REF123456789")
    private String refundTransactionId;

    @Schema(description = "Original transaction ID for which refund was initiated", example = "TXN987654321")
    private String transactionId;

    @Schema(description = "Merchant identifier", example = "M12345")
    private String merchantId;

    @Schema(description = "Refund amount in paise", example = "5000")
    private double amount;

    @Schema(description = "Refund status (e.g., SUCCESS, PENDING, FAILED)", example = "SUCCESS")
    private String status;
}
