package com.phonepe.payment.dqr.entity;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Entity
@Table(name = "dqr_refund_transactions_request")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DqrRefundTransactionRequest {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(hidden = true) // Hide internal DB id from Swagger docs
    private Long id;

    @Schema(description = "Merchant identifier registered with PhonePe", example = "MERCHANT98765")
    private String merchantId;

    @Schema(description = "Unique transaction ID generated by PhonePe", example = "TXN987654321")
    private String transactionId;

    @Schema(description = "Unique originalTransactionId ID generated by PhonePe", example = "TXN987654321")
    private String originalTransactionId;

    @Schema(description = "Unique order ID from the merchant", example = "ORD12345")
    private String merchantOrderId;

    @Schema(description = "Detailed message about the cancellation result", example = "refund")
    private String message;

    @Schema(description = "Unique merchant identifier", example = "MERCHANTPROVIDER")
    private String provider;

    @Schema(description = "Refund amount in paise", example = "5000")
    private Long amount;

    @Schema(description = "Timestamp when the refund request was created", example = "2025-09-04T12:45:00")
    private LocalDateTime createdAt;
}
